"""Build a (one-instance, many-instances) image-pair file for Stage 2 grounding,
using COCO category counts.

For each chosen noun, we pull:
  • one image where COCO has exactly 1 instance of that category, and
  • one image where COCO has ≥ 3 instances of that category.

Usage:
    python3 scripts/build_image_pairs_coco.py \\
        --coco-root /data/coco \\
        --split val2017 \\
        --out data/plurality/image_pairs.tsv \\
        --pairs-per-noun 10
"""
from __future__ import annotations

import argparse
import random
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))


# COCO category names → operator-test noun. Adjust to match your text-pair list.
COCO_CATEGORY_TO_NOUN = {
    "cat":      "cat",
    "dog":      "dog",
    "person":   "person",
    "bird":     "bird",
    "horse":    "horse",
    "sheep":    "sheep",
    "cow":      "cow",
    "elephant": "elephant",
    "bear":     "bear",
    "zebra":    "zebra",
    "giraffe":  "giraffe",
    "bottle":   "bottle",
    "cup":      "cup",
    "bowl":     "bowl",
    "apple":    "apple",
    "orange":   "orange",
    "chair":    "chair",
    "couch":    "couch",
    "bed":      "bed",
    "book":     "book",
}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--coco-root", required=True)
    parser.add_argument("--split", default="val2017")
    parser.add_argument("--out", required=True)
    parser.add_argument("--pairs-per-noun", type=int, default=10)
    parser.add_argument("--many-threshold", type=int, default=3,
                        help="instances ≥ this count = 'many'")
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()

    try:
        from pycocotools.coco import COCO
    except ImportError:
        sys.exit("Install pycocotools first: pip install pycocotools")

    rng = random.Random(args.seed)
    inst_path = Path(args.coco_root) / "annotations" / f"instances_{args.split}.json"
    img_dir = Path(args.coco_root) / "images" / args.split
    coco = COCO(str(inst_path))

    # category_id ↔ name
    cat_id_to_name = {c["id"]: c["name"] for c in coco.loadCats(coco.getCatIds())}
    name_to_cat_id = {v: k for k, v in cat_id_to_name.items()}

    pairs: list[tuple[Path, Path, str]] = []

    for coco_name, noun in COCO_CATEGORY_TO_NOUN.items():
        cat_id = name_to_cat_id.get(coco_name)
        if cat_id is None:
            continue

        # Bucket images by instance count of this category.
        ones: list[int] = []
        manys: list[int] = []
        for img_id in coco.getImgIds(catIds=[cat_id]):
            ann_ids = coco.getAnnIds(imgIds=img_id, catIds=[cat_id])
            n = len(ann_ids)
            if n == 1:
                ones.append(img_id)
            elif n >= args.many_threshold:
                manys.append(img_id)

        if not ones or not manys:
            continue

        rng.shuffle(ones); rng.shuffle(manys)
        n_pairs = min(args.pairs_per_noun, len(ones), len(manys))
        for i in range(n_pairs):
            one_meta = coco.loadImgs(ones[i])[0]
            many_meta = coco.loadImgs(manys[i])[0]
            pairs.append((
                img_dir / one_meta["file_name"],
                img_dir / many_meta["file_name"],
                noun,
            ))

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        f.write("# auto-generated by scripts/build_image_pairs_coco.py\n")
        for one, many, noun in pairs:
            f.write(f"{one}\t{many}\t{noun}\n")

    print(f"Wrote {len(pairs)} image pairs to {out_path}")
    print(f"Covered nouns: {sorted({n for _, _, n in pairs})}")


if __name__ == "__main__":
    main()
